language: node_js
node_js:
  - 'node' # use latest stable nodejs version
script:
{{# if coverage}}
  - npm run coverage # jest test with coverage flag does coverage too
{{else}}
  - npm run test
{{/if}}
{{# if coverage}}
after_script:
  - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls' # sends the coverage report to coveralls
{{/if}}